# Generated by Django 3.2.15 on 2023-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=350, unique=True, verbose_name='адрес места')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('last_request', models.DateField(null=True, verbose_name='дата последнего запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('longitude', 'latitude'), name='unique_coordinates'),
        ),
    ]
