# Generated by Django 3.2.15 on 2023-11-23 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_coordinates',
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9, verbose_name='долгота'),
        ),
    ]
