# Generated by Django 3.2.15 on 2023-10-28 00:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20231028_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='стоимость позиции'),
        ),
    ]
