# Generated by Django 3.2.15 on 2023-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('ASSEMBLY', 'На сборке'), ('DELIVERY', 'Доставляется'), ('DONE', 'Доставлен')], default='UNPROCESSED', max_length=50, verbose_name='статус заказа'),
        ),
    ]
