# Generated by Django 3.2.15 on 2023-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAID_BY_SITE', 'Оплачен через сайт'), ('UNPAID_BY_SITE', 'Не оплачен через сайт'), ('CASH_ON_DELIVERY', 'Наличными при получении'), ('CASHLESS_ON_DELIVERY', 'Электронно при получении')], db_index=True, default='UNPAID_BY_SITE', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('ASSEMBLY', 'Готовится'), ('DELIVERY', 'Доставляется'), ('DONE', 'Исполнен')], db_index=True, default='UNPROCESSED', max_length=50, verbose_name='статус заказа'),
        ),
    ]
